FRW-8639: add opentelemetry integrator script
spryker/opentelemetry-installer pull request #1
Opened 2024-09-23 09:27 UTC by kraal-spryker

## PR Description
Ticket: https://spryker.atlassian.net/browse/FRW-8639

TBD

## Checklist
- [ ] I agree with the Code Contribution License Agreement in CONTRIBUTING.md

2024-12-10 12:08 UTC, kraal-spryker commented
i see that you removed composer.json related changes. is it not needed anymore?

2024-12-10 12:12 UTC, gechetspr commented
> i see that you removed composer.json related changes. is it not needed anymore?

We don't need any files to be downloaded first. Currently all installed via `composer require`

2024-12-10 12:43 UTC, annakotiuk commented on README.md
> +This is a simple script to integrate OpenTelemetry in the project. The script `otel_integrator.sh` should be copied to the root of the project.
How do you like AI improvement?

This guide explains how to use the otel_integrator.sh script to integrate OpenTelemetry into your project.

### Script Overview

The otel_integrator.sh script automates the integration of OpenTelemetry into a project. It should be copied to the root of your project for proper functionality.

Parameters

**- Project Namespace (optional):**
  - Default: Pyz
  - Specifies the namespace of the project.
**- Deploy File Name (optional):**
  - Default: deploy.yml
  - Specifies the name of the deploy configuration file.
**- Install Script Name (optional):**
  - Default: config/install/docker.yml
  - Specifies the path to the installation script.

### Prerequisites
yq Tool:
Ensure the yq tool is installed on your system.
Example installation via Homebrew:
brew install yq

### Execution Steps

Copy the otel_integrator.sh script to the root directory of your project:
cp otel_integrator.sh /path/to/your/project/root
Run the script with the required parameters (or use defaults):
./otel_integrator.sh [PROJECT_NAMESPACE] [DEPLOY_FILE_NAME] [INSTALL_SCRIPT_NAME]
Example:

./otel_integrator.sh Pyz deploy.yml config/install/docker.yml
The script will modify the specified files as needed to integrate OpenTelemetry.

### Post-Script Review

After running the script:

**Verify the Deploy File:**
Review changes in the deploy file (deploy.yml by default) to ensure they align with your expectations.
**Run the Docker SDK:**
Start the Docker SDK using the updated deploy file:
docker/sdk boot [YOUR_DEPLOY_FILE_NAME]
**Validate Extensions:**
Confirm that the blackfire and opentelemetry extensions are not enabled simultaneously.

### Notes

Modify default values in the script if your project has specific requirements.
For troubleshooting, refer to logs or console output from the script execution.

2024-12-10 12:46 UTC, annakotiuk commented on README.md
> +This is a simple script to integrate OpenTelemetry in the project. The script `otel_integrator.sh` should be copied to the root of the project.
Or just fix errors: 
This is a simple script to integrate OpenTelemetry into the project

2024-12-10 12:46 UTC, annakotiuk commented on README.md
> +First param is a project namespace. Default to `Pyz`.
The first parameter is the project namespace, which defaults to Pyz.

2024-12-10 12:47 UTC, annakotiuk commented on README.md
> +Third param is install script name. Default to `config/install/docker.yml`
The third parameter is the install script name, which defaults to config/install/docker.yml.

2024-12-10 12:48 UTC, annakotiuk commented on README.md
> +Tool `yq` should be installed in the system. E.g. via brew `brew install yq`
The yq tool must be installed `on` the system

2024-12-10 12:50 UTC, annakotiuk commented on README.md
> +After the script is done, review your changes. Make sure that deploy file is updated and run `docker/sdk boot {%YOUR_FILE_NAME%}`. Make sure that `blackfire` extension and `opentelemetry` extension a
`at` the same time.

2024-12-17 09:36 UTC, olhalivitchuk requested changes

2024-12-17 09:36 UTC, olhalivitchuk commented on README.md
> +    - Default: volhovm/spryker-8.3-alpine-3.20
Aren't we going to put the image in spryker repo?

2024-12-17 16:05 UTC, olhalivitchuk approved these changes

2024-12-17 16:48 UTC, asmarovydlo approved these changes

2024-12-19 09:34 UTC, merged